"""pkg76 format-level tests — no bpy dependency.

Exercises the parser against the committed `synthetic_min.blend` fixture.
The fixture is regenerated by `tests/fixtures/build_synthetic_min.py` when
fields ever change; CI does not run that script.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tools.blend_import.reader import BlendFile
from tools.blend_import.sdna import decode_header, FileHeader


FIXTURE = Path(__file__).parent / "fixtures" / "synthetic_min.blend"


pytestmark = pytest.mark.skipif(not FIXTURE.exists(),
                                reason="synthetic_min.blend fixture not committed")


def test_header_decode():
    raw = FIXTURE.read_bytes()
    h: FileHeader = decode_header(raw[:17])
    # Authored with Blender 5.1 (`compress=False`) — extended 17-byte header.
    assert h.header_size == 17
    assert h.pointer_size == 8
    assert h.little_endian is True
    assert h.version.startswith("05")  # Blender 5.x


def test_block_walk_finds_required_codes():
    bf = BlendFile.from_path(FIXTURE)
    # The fixture has exactly one of each parity-scope datablock.
    assert len(bf.by_code["SC"]) == 1, "expected 1 Scene block"
    assert len(bf.by_code["ME"]) == 1, "expected 1 Mesh block"
    assert len(bf.by_code["CA"]) == 1, "expected 1 Camera block"
    assert len(bf.by_code["LA"]) == 1, "expected 1 Lamp block"
    assert len(bf.by_code["MA"]) == 1, "expected 1 Material block"
    assert len(bf.by_code["WO"]) == 1, "expected 1 World block"
    assert len(bf.by_code["GLOB"]) == 1
    assert len(bf.by_code["DNA1"]) == 1
    assert len(bf.by_code["ENDB"]) == 1
    # Object count: camera + sun + cube.
    assert len(bf.by_code["OB"]) == 3


def test_sdna_struct_table():
    bf = BlendFile.from_path(FIXTURE)
    # Three known structs we read fields from in scene_builder.
    for type_name in ("Scene", "Object", "Mesh", "Camera", "Lamp",
                      "Material", "World", "FileGlobal",
                      "AttributeStorage", "Attribute", "AttributeArray",
                      "bNode", "bNodeSocket", "bNodeSocketValueRGBA"):
        s = bf.sdna.struct_for(type_name)
        assert s is not None, f"SDNA missing struct {type_name!r}"
        assert s.size > 0


def test_camera_field_decode():
    """Decode three Camera fields without bpy and assert exact values."""
    bf = BlendFile.from_path(FIXTURE)
    cam_blk = bf.by_code["CA"][0]
    cam_struct = bf.struct_of(cam_blk)
    # Authored values from build_synthetic_min.py.
    assert bf.read_float(cam_blk, cam_struct, "lens")[0] == pytest.approx(42.0, abs=1e-3)
    assert bf.read_float(cam_blk, cam_struct, "sensor_x")[0] == pytest.approx(36.0, abs=1e-3)
    assert bf.read_float(cam_blk, cam_struct, "clipsta")[0] == pytest.approx(0.05, abs=1e-3)


def test_material_legacy_rgb_decode():
    """Material RGB fields are readable even when use_nodes is true (legacy
    cache fields persist)."""
    bf = BlendFile.from_path(FIXTURE)
    mat_blk = bf.by_code["MA"][0]
    mat_struct = bf.struct_of(mat_blk)
    # The legacy r/g/b fields exist; their concrete value is whatever Blender
    # writes for a node-driven material — we only assert decodability + range.
    r = bf.read_float(mat_blk, mat_struct, "r")[0]
    g = bf.read_float(mat_blk, mat_struct, "g")[0]
    b = bf.read_float(mat_blk, mat_struct, "b")[0]
    for c in (r, g, b):
        assert 0.0 <= c <= 1.0


def test_pointer_resolution():
    """FileGlobal.curscene → SC block round-trip."""
    bf = BlendFile.from_path(FIXTURE)
    glob = bf.by_code["GLOB"][0]
    fg = bf.sdna.struct_for("FileGlobal")
    ptr = bf.read_pointer(glob, fg, "curscene")
    sc = bf.follow(ptr)
    assert sc is not None
    assert sc.code == "SC"
