"""pkg76 format-level tests — no bpy dependency.

Exercises the parser against the committed `synthetic_min.blend` fixture.
The fixture is regenerated by `tests/fixtures/build_synthetic_min.py` when
fields ever change; CI does not run that script.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from tools.blend_import.reader import BlendFile
from tools.blend_import.sdna import decode_header, FileHeader


FIXTURE = Path(__file__).parent / "fixtures" / "synthetic_min.blend"


pytestmark = pytest.mark.skipif(not FIXTURE.exists(),
                                reason="synthetic_min.blend fixture not committed")


def test_header_decode():
    raw = FIXTURE.read_bytes()
    h: FileHeader = decode_header(raw[:17])
    # Authored with Blender 5.1 (`compress=False`) — extended 17-byte header.
    assert h.header_size == 17
    assert h.pointer_size == 8
    assert h.little_endian is True
    assert h.version.startswith("05")  # Blender 5.x


def test_block_walk_finds_required_codes():
    bf = BlendFile.from_path(FIXTURE)
    # The fixture has exactly one of each parity-scope datablock.
    assert len(bf.by_code["SC"]) == 1, "expected 1 Scene block"
    assert len(bf.by_code["ME"]) == 1, "expected 1 Mesh block"
    assert len(bf.by_code["CA"]) == 1, "expected 1 Camera block"
    assert len(bf.by_code["LA"]) == 1, "expected 1 Lamp block"
    assert len(bf.by_code["MA"]) == 1, "expected 1 Material block"
    assert len(bf.by_code["WO"]) == 1, "expected 1 World block"
    assert len(bf.by_code["GLOB"]) == 1
    assert len(bf.by_code["DNA1"]) == 1
    assert len(bf.by_code["ENDB"]) == 1
    # Object count: camera + sun + cube.
    assert len(bf.by_code["OB"]) == 3


def test_sdna_struct_table():
    bf = BlendFile.from_path(FIXTURE)
    # Three known structs we read fields from in scene_builder.
    for type_name in ("Scene", "Object", "Mesh", "Camera", "Lamp",
                      "Material", "World", "FileGlobal",
                      "AttributeStorage", "Attribute", "AttributeArray",
                      "bNode", "bNodeSocket", "bNodeSocketValueRGBA"):
        s = bf.sdna.struct_for(type_name)
        assert s is not None, f"SDNA missing struct {type_name!r}"
        assert s.size > 0


def test_camera_field_decode():
    """Decode three Camera fields without bpy and assert exact values."""
    bf = BlendFile.from_path(FIXTURE)
    cam_blk = bf.by_code["CA"][0]
    cam_struct = bf.struct_of(cam_blk)
    # Authored values from build_synthetic_min.py.
    assert bf.read_float(cam_blk, cam_struct, "lens")[0] == pytest.approx(42.0, abs=1e-3)
    assert bf.read_float(cam_blk, cam_struct, "sensor_x")[0] == pytest.approx(36.0, abs=1e-3)
    assert bf.read_float(cam_blk, cam_struct, "clipsta")[0] == pytest.approx(0.05, abs=1e-3)


def test_material_legacy_rgb_decode():
    """Material RGB fields are readable even when use_nodes is true (legacy
    cache fields persist)."""
    bf = BlendFile.from_path(FIXTURE)
    mat_blk = bf.by_code["MA"][0]
    mat_struct = bf.struct_of(mat_blk)
    # The legacy r/g/b fields exist; their concrete value is whatever Blender
    # writes for a node-driven material — we only assert decodability + range.
    r = bf.read_float(mat_blk, mat_struct, "r")[0]
    g = bf.read_float(mat_blk, mat_struct, "g")[0]
    b = bf.read_float(mat_blk, mat_struct, "b")[0]
    for c in (r, g, b):
        assert 0.0 <= c <= 1.0


def test_pointer_resolution():
    """FileGlobal.curscene → SC block round-trip."""
    bf = BlendFile.from_path(FIXTURE)
    glob = bf.by_code["GLOB"][0]
    fg = bf.sdna.struct_for("FileGlobal")
    ptr = bf.read_pointer(glob, fg, "curscene")
    sc = bf.follow(ptr)
    assert sc is not None
    assert sc.code == "SC"


def test_import_blend_into_real_renderer_no_dynamic_attr():
    """pkg100 regression: end-to-end import_blend against the real pybind11
    Renderer using the committed synthetic_min.blend (no bpy needed).

    The original pkg100 fix moved ``_cam_intrinsics`` off the renderer attribute,
    but missed a second site that still did ``renderer._blend_import_stats = stats``.
    On the real ``astroray.Renderer`` (no ``__dict__``) that second assignment
    raised AttributeError, so any real-world import would fail. The
    bpy-gated regression test in ``test_blend_import_roundtrip.py`` skipped
    in CI (no bpy), so this regression rode into main. The current fix uses
    a ``stats_out`` out-parameter; this test exercises that path with no bpy.
    """
    astroray = pytest.importorskip("astroray")
    from tools.blend_import import import_blend

    renderer = astroray.Renderer()
    stats: dict = {}
    result = import_blend(
        FIXTURE, renderer=renderer, width=128, height=128, stats_out=stats,
    )
    assert result is renderer
    assert isinstance(stats, dict)
    # synthetic_min.blend has no real camera intrinsics; just verify the
    # function returned without raising AttributeError on the real binding.


def test_mesh_poly_offset_indices_fallback():
    """pkg76-followup (BMW27 fix): verify _mesh_face_offsets tries attribute
    lookup before falling back to legacy paths.

    synthetic_min.blend (Blender 5.1) stores poly_offset_indices as an
    attribute; older Blender stored it as a direct Mesh pointer; even older
    stored MPoly[].loopstart arrays. The importer must handle all three layouts.
    """
    from tools.blend_import.scene_builder import _mesh_face_offsets

    bf = BlendFile.from_path(FIXTURE)
    me_blk = bf.by_code["ME"][0]
    me_struct = bf.struct_of(me_blk)
    totpoly = bf.read_int(me_blk, me_struct, "totpoly")
    if totpoly == 0:
        pytest.skip("synthetic_min.blend has no polygons")

    # Minimal stub context — only .blend is accessed by _mesh_face_offsets.
    class MinimalCtx:
        def __init__(self, blend):
            self.blend = blend
        def warn(self, msg):
            pass

    ctx = MinimalCtx(bf)
    offsets = _mesh_face_offsets(ctx, me_blk, totpoly)
    assert offsets is not None, "poly_offset_indices read failed"
    assert len(offsets) == totpoly + 1, f"expected {totpoly+1} offsets, got {len(offsets)}"
    # Offsets must be monotonic non-decreasing.
    for i in range(totpoly):
        assert offsets[i] <= offsets[i + 1], f"non-monotonic offsets at poly {i}"


# ---------------------------------------------------------------------------
# Two-mesh fixture: DATA-block "old" addresses are only unique per owning ID.
#
# Blender writes each mesh's Attribute/AttributeArray/AttributeSingle DNA
# records from ResourceScope temporaries (attribute_storage.cc,
# attribute_storage_blend_write_prepare), so separate meshes in one file get
# DATA blocks with identical "old" addresses. readfile.cc scopes the DATA map
# per ID block (read_libblock → read_data_into_datamap → oldnewmap_clear).
# A file-global last-write-wins map handed the plane the sphere's topology.

TWO_MESH = Path(__file__).parent / "fixtures" / "two_mesh.blend"

two_mesh_only = pytest.mark.skipif(not TWO_MESH.exists(),
                                   reason="two_mesh.blend fixture not committed")


def _mesh_attrs_ptr(bf: BlendFile, me):
    """Raw Mesh.attribute_storage.dna_attributes pointer of *me*."""
    import struct as _struct
    me_struct = bf.struct_of(me)
    ast = bf.sdna.struct_for("AttributeStorage")
    base = me.payload_offset + me_struct.by_name["attribute_storage"].offset
    fmt = bf.header.endian_char + bf.header.ptr_fmt
    (ptr,) = _struct.unpack_from(fmt, bf.buf, base + ast.by_name["dna_attributes"].offset)
    return ptr


@two_mesh_only
def test_two_mesh_fixture_has_cross_id_old_collisions():
    """Premise check: the fixture really does contain duplicate DATA 'old'
    addresses, and every duplicate straddles two different ID blocks."""
    bf = BlendFile.from_path(TWO_MESH)
    assert len(bf.by_code["ME"]) == 2
    owner = None
    owners = []
    for b in bf.blocks:
        if b.code != "DATA":
            owner = b
        owners.append(owner)
    by_old: dict[int, list] = {}
    for b, o in zip(bf.blocks, owners):
        if b.code == "DATA" and b.old:
            by_old.setdefault(b.old, []).append(o)
    dups = {k: v for k, v in by_old.items() if len(v) > 1}
    assert dups, "fixture no longer exhibits the collision — regenerate it"
    for old, blk_owners in dups.items():
        assert len({id(o) for o in blk_owners}) == len(blk_owners), \
            f"same-ID collision at {old:#x} (Blender treats this as corruption)"


@two_mesh_only
def test_follow_scoped_to_owning_id():
    bf = BlendFile.from_path(TWO_MESH)
    me_a, me_b = bf.by_code["ME"]
    ptr_a, ptr_b = _mesh_attrs_ptr(bf, me_a), _mesh_attrs_ptr(bf, me_b)
    assert ptr_a == ptr_b, "fixture premise: both meshes share the Attribute[] address"
    blk_a = bf.follow(ptr_a, scope=me_a)
    blk_b = bf.follow(ptr_b, scope=me_b)
    assert blk_a is not None and blk_b is not None
    assert blk_a is not blk_b
    ia, ib = bf.blocks.index(me_a), bf.blocks.index(me_b)
    ja, jb = bf.blocks.index(blk_a), bf.blocks.index(blk_b)
    # Each resolved DATA block lies in its own mesh's trailing DATA span.
    assert ia < ja < ib < jb
    # ID pointers still resolve without a scope.
    glob = bf.by_code["GLOB"][0]
    fg = bf.sdna.struct_for("FileGlobal")
    assert bf.follow(bf.read_pointer(glob, fg, "curscene")).code == "SC"
    # An unscoped lookup of an ambiguous DATA address must fail loudly.
    with pytest.raises(ValueError, match="ambiguous"):
        bf.follow(ptr_a)


class _CountingRenderer:
    def __init__(self):
        self.triangles = []
        self.materials = []

    def create_material(self, kind, color, params):
        self.materials.append((kind, list(color), dict(params)))
        return len(self.materials) - 1

    def add_triangle(self, v0, v1, v2, mat_id):
        self.triangles.append((tuple(v0), tuple(v1), tuple(v2), mat_id))

    def set_background_color(self, c):
        pass

    def setup_camera(self, *a, **k):
        pass


@two_mesh_only
def test_build_scene_two_separate_meshes():
    """Plane (1 quad) + UV sphere (8 segments × 4 rings) as separate mesh
    datablocks import without the plane reading the sphere's corner_verts."""
    from tools.blend_import.scene_builder import build_scene
    bf = BlendFile.from_path(TWO_MESH)
    r = _CountingRenderer()
    stats = build_scene(bf, r, on_warning=lambda m: None)
    # plane: 2 tris; sphere: 8 top tris + 8 bottom tris + 16 quads → 48 tris.
    assert stats["triangles"] == 2 + 48
    assert len(r.triangles) == 50
    # Plane at z=0 spans ±2; every sphere vertex sits within radius 1 of (0,0,1).
    plane = [t for t in r.triangles if all(abs(v[2]) < 1e-6 for v in t[:3])]
    assert len(plane) == 2
    for t in r.triangles:
        for v in t[:3]:
            assert abs(v[0]) <= 2.0 + 1e-6 and abs(v[1]) <= 2.0 + 1e-6
