"""pkg67: flat-space regression.

Option α of pkg67 is purely additive: it adds MinkowskiMetric, a redshift
method on SampledWavelengths, and exposes frequencyShift on
GRSpectralResult. None of these are wired into the production flat-space
hot path (the existing `BlackHole::isGRObject()` dispatch is preserved).
Therefore the flat-space render is bit-identical before/after pkg67.

This test verifies:

1. The astroray module exposes a "minkowski" metric via MetricRegistry
   (smoke).
2. If `tests/reference/pkg67_flat_baseline_256.png` exists, an equivalent
   render matches it at SSIM ≥ 0.999.

The baseline image is generated by `benchmarks/pkg67_flat_perf.py` and
committed alongside this PR. If the baseline is missing the SSIM check is
skipped — the smoke assertion still runs.
"""

import os
import pytest


REFERENCE_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "reference",
    "pkg67_flat_baseline_256.png",
)


@pytest.fixture(scope="module")
def astroray_module():
    try:
        import astroray
    except ImportError as e:
        pytest.skip(f"astroray module not available: {e}")
    return astroray


def test_minkowski_metric_registered(astroray_module):
    """MinkowskiMetric should be queryable through the registry."""
    if not hasattr(astroray_module, "metric_registry_names"):
        pytest.skip("astroray build predates pkg40 MetricRegistry exposure")
    names = list(astroray_module.metric_registry_names())
    assert "minkowski" in names, (
        f"'minkowski' not in MetricRegistry names: {names}"
    )


def test_flat_baseline_ssim(astroray_module):
    if not os.path.exists(REFERENCE_PATH):
        pytest.skip(
            f"flat baseline not present at {REFERENCE_PATH}; "
            "run benchmarks/pkg67_flat_perf.py --capture-baseline to generate"
        )

    try:
        import numpy as np
        from PIL import Image
        from skimage.metrics import structural_similarity as ssim
    except ImportError as e:
        pytest.skip(f"image-compare deps unavailable: {e}")

    # Re-render the same flat scene at the same seed and resolution.
    try:
        from benchmarks import pkg67_flat_perf as bench  # type: ignore
    except ImportError:
        pytest.skip("benchmarks/pkg67_flat_perf.py not present")

    rendered = bench.render_baseline(astroray_module)
    reference = np.asarray(Image.open(REFERENCE_PATH).convert("RGB"),
                           dtype=np.float32) / 255.0
    s = ssim(reference, rendered, channel_axis=2, data_range=1.0)
    assert s >= 0.999, f"flat-space SSIM regression: {s:.6f} < 0.999"
