// optix_pipeline.cpp — pkg299 OptiX context, module, program groups, pipeline,
// shader binding table and the two wavefront launches (closest hit, shadow).
//
// Structure follows the NVIDIA OptiX SDK 9.1 samples optixTriangle and
// optixRaycasting (BSD-3-Clause): optixModuleCreate from embedded OptiX-IR,
// one raygen/miss/hitgroup program group per entry point, header-only SBT
// records, stack sizes from optixPipelineSetStackSizeFromCallDepths (trace
// depth 1, no callables, IAS -> GAS). Disk caching of the
// compiled module uses OptiX's built-in cache (enabled by default,
// optixDeviceContextSetCacheEnabled).
//
// The denoiser (pkg70) keeps its own OptixDeviceContext on the same CUDA
// primary context; the two do not share state (see optix_internal.h).

#ifdef ASTRORAY_OPTIX_TRAVERSAL

#include "optix_internal.h"
#include <optix_function_table_definition.h>   // g_astrorayOptixTraversalFunctionTable

#include <cuda_runtime.h>

#include <algorithm>
#include <cstdio>
#include <mutex>
#include <vector>

#include "astroray/gpu_optix_traversal.h"
#include "optix_launch_params.h"

// Generated by cmake/EmbedBinary.cmake from optix_trace_programs.cu.
extern "C" const unsigned char astroray_optix_trace_programs_ir[];
extern "C" const unsigned long long astroray_optix_trace_programs_ir_size;

namespace astroray {
namespace optix_trav {

namespace {

struct alignas(OPTIX_SBT_RECORD_ALIGNMENT) SbtRecord {
    char header[OPTIX_SBT_RECORD_HEADER_SIZE];
};

struct Pipeline {
    bool tried = false;
    bool ok = false;
    std::string error;
    OptixDeviceContext ctx = nullptr;
    OptixModule module = nullptr;
    OptixProgramGroup rgClosest = nullptr, rgShadow = nullptr;
    OptixProgramGroup msClosest = nullptr, msShadow = nullptr;
    OptixProgramGroup hitGroup = nullptr;
    OptixPipeline pipe = nullptr;
    CUdeviceptr dRgClosest = 0, dRgShadow = 0, dMiss = 0, dHit = 0;
    OptixShaderBindingTable sbtClosest{}, sbtShadow{};
    CUdeviceptr dParams = 0;
};

Pipeline& P() {
    static Pipeline p;
    return p;
}

std::mutex& initMutex() {
    static std::mutex m;
    return m;
}

void logCallback(unsigned int level, const char* tag, const char* msg, void*) {
    if (level <= 2)   // fatal / error only
        std::fprintf(stderr, "[pkg299 OptiX %s] %s\n", tag ? tag : "?", msg ? msg : "");
}

OptixProgramGroup makeGroup(OptixDeviceContext ctx, const OptixProgramGroupDesc& desc) {
    OptixProgramGroupOptions opts = {};
    OptixProgramGroup g = nullptr;
    char log[2048]; size_t logSize = sizeof(log);
    OptixResult r = optixProgramGroupCreate(ctx, &desc, 1, &opts, log, &logSize, &g);
    if (r != OPTIX_SUCCESS)
        throw std::runtime_error(std::string("[pkg299 OptiX] optixProgramGroupCreate -> ") +
                                 optixGetErrorName(r) + ": " + log);
    return g;
}

CUdeviceptr uploadRecord(OptixProgramGroup g, int count = 1) {
    std::vector<SbtRecord> recs(count);
    for (auto& rec : recs) ASTRORAY_OPTIX_TRAV_CHECK(optixSbtRecordPackHeader(g, &rec));
    CUdeviceptr d = 0;
    ASTRORAY_OPTIX_TRAV_CUDA(cudaMalloc(reinterpret_cast<void**>(&d), sizeof(SbtRecord) * count));
    ASTRORAY_OPTIX_TRAV_CUDA(cudaMemcpy(reinterpret_cast<void*>(d), recs.data(),
                                        sizeof(SbtRecord) * count, cudaMemcpyHostToDevice));
    return d;
}

// Reverse-order teardown of whatever initPipeline created (partial-init path).
void destroyPipeline(Pipeline& p) {
    auto freeDev = [](CUdeviceptr& d) {
        if (d) cudaFree(reinterpret_cast<void*>(d));
        d = 0;
    };
    freeDev(p.dParams); freeDev(p.dHit); freeDev(p.dMiss);
    freeDev(p.dRgShadow); freeDev(p.dRgClosest);
    if (p.pipe) optixPipelineDestroy(p.pipe);
    for (OptixProgramGroup* g : { &p.hitGroup, &p.msShadow, &p.msClosest, &p.rgShadow, &p.rgClosest }) {
        if (*g) optixProgramGroupDestroy(*g);
        *g = nullptr;
    }
    if (p.module) optixModuleDestroy(p.module);
    if (p.ctx) optixDeviceContextDestroy(p.ctx);
    p.pipe = nullptr; p.module = nullptr; p.ctx = nullptr;
    p.sbtClosest = {}; p.sbtShadow = {};
}

void initPipeline(Pipeline& p) {
    ASTRORAY_OPTIX_TRAV_CHECK(optixInit());
    ASTRORAY_OPTIX_TRAV_CUDA(cudaFree(0));   // make sure the primary context exists

    OptixDeviceContextOptions ctxOpts = {};
    ctxOpts.logCallbackFunction = &logCallback;
    ctxOpts.logCallbackLevel    = 2;
    ASTRORAY_OPTIX_TRAV_CHECK(optixDeviceContextCreate(/*current CUDA ctx*/ 0, &ctxOpts, &p.ctx));

    unsigned int rtcore = 0;
    ASTRORAY_OPTIX_TRAV_CHECK(optixDeviceContextGetProperty(
        p.ctx, OPTIX_DEVICE_PROPERTY_RTCORE_VERSION, &rtcore, sizeof(rtcore)));
    if (rtcore == 0)
        throw std::runtime_error("[pkg299 OptiX] device has no RT cores");

    OptixModuleCompileOptions modOpts = {};
    OptixPipelineCompileOptions pipeOpts = {};
    pipeOpts.usesMotionBlur        = 0;
    // Root is either one GAS (flat scene) or a single-level IAS (pkg114).
    pipeOpts.traversableGraphFlags = OPTIX_TRAVERSABLE_GRAPH_FLAG_ALLOW_ANY;
    pipeOpts.numPayloadValues      = 5;   // t, prim, b1, b2, instance
    pipeOpts.numAttributeValues    = 2;   // built-in triangle barycentrics
    pipeOpts.exceptionFlags        = OPTIX_EXCEPTION_FLAG_NONE;
    pipeOpts.pipelineLaunchParamsVariableName = "params";
    pipeOpts.usesPrimitiveTypeFlags = OPTIX_PRIMITIVE_TYPE_FLAGS_TRIANGLE;

    {
        char log[4096]; size_t logSize = sizeof(log);
        OptixResult r = optixModuleCreate(
            p.ctx, &modOpts, &pipeOpts,
            reinterpret_cast<const char*>(astroray_optix_trace_programs_ir),
            static_cast<size_t>(astroray_optix_trace_programs_ir_size),
            log, &logSize, &p.module);
        if (r != OPTIX_SUCCESS)
            throw std::runtime_error(std::string("[pkg299 OptiX] optixModuleCreate -> ") +
                                     optixGetErrorName(r) + ": " + log);
    }

    OptixProgramGroupDesc d = {};
    d.kind = OPTIX_PROGRAM_GROUP_KIND_RAYGEN;
    d.raygen.module = p.module;
    d.raygen.entryFunctionName = "__raygen__closest";
    p.rgClosest = makeGroup(p.ctx, d);
    d.raygen.entryFunctionName = "__raygen__shadow";
    p.rgShadow = makeGroup(p.ctx, d);

    d = {};
    d.kind = OPTIX_PROGRAM_GROUP_KIND_MISS;
    d.miss.module = p.module;
    d.miss.entryFunctionName = "__miss__closest";
    p.msClosest = makeGroup(p.ctx, d);
    d.miss.entryFunctionName = "__miss__shadow";
    p.msShadow = makeGroup(p.ctx, d);

    d = {};
    d.kind = OPTIX_PROGRAM_GROUP_KIND_HITGROUP;
    d.hitgroup.moduleCH = p.module;
    d.hitgroup.entryFunctionNameCH = "__closesthit__closest";
    p.hitGroup = makeGroup(p.ctx, d);

    OptixProgramGroup groups[] = { p.rgClosest, p.rgShadow, p.msClosest, p.msShadow, p.hitGroup };
    OptixPipelineLinkOptions linkOpts = {};
    linkOpts.maxTraceDepth = 1;
    {
        char log[2048]; size_t logSize = sizeof(log);
        OptixResult r = optixPipelineCreate(p.ctx, &pipeOpts, &linkOpts, groups,
                                            sizeof(groups) / sizeof(groups[0]),
                                            log, &logSize, &p.pipe);
        if (r != OPTIX_SUCCESS)
            throw std::runtime_error(std::string("[pkg299 OptiX] optixPipelineCreate -> ") +
                                     optixGetErrorName(r) + ": " + log);
    }

    // Stack sizes from the call depths (OptiX 9.1 host API): one trace level, no
    // callables, traversable graph IAS -> GAS (depth 2).
    ASTRORAY_OPTIX_TRAV_CHECK(optixPipelineSetStackSizeFromCallDepths(
        p.pipe, /*maxTraceDepth*/ 1, /*maxCC*/ 0, /*maxDCFromState*/ 0,
        /*maxDCFromTraversal*/ 0, /*maxTraversableGraphDepth*/ 2));

    p.dRgClosest = uploadRecord(p.rgClosest);
    p.dRgShadow  = uploadRecord(p.rgShadow);
    {
        // Miss records: [0] closest, [1] shadow (missSBTIndex in optixTrace).
        SbtRecord recs[2];
        ASTRORAY_OPTIX_TRAV_CHECK(optixSbtRecordPackHeader(p.msClosest, &recs[0]));
        ASTRORAY_OPTIX_TRAV_CHECK(optixSbtRecordPackHeader(p.msShadow, &recs[1]));
        ASTRORAY_OPTIX_TRAV_CUDA(cudaMalloc(reinterpret_cast<void**>(&p.dMiss), sizeof(recs)));
        ASTRORAY_OPTIX_TRAV_CUDA(cudaMemcpy(reinterpret_cast<void*>(p.dMiss), recs,
                                            sizeof(recs), cudaMemcpyHostToDevice));
    }
    p.dHit = uploadRecord(p.hitGroup);

    OptixShaderBindingTable sbt = {};
    sbt.missRecordBase          = p.dMiss;
    sbt.missRecordStrideInBytes = sizeof(SbtRecord);
    sbt.missRecordCount         = 2;
    sbt.hitgroupRecordBase          = p.dHit;
    sbt.hitgroupRecordStrideInBytes = sizeof(SbtRecord);
    sbt.hitgroupRecordCount         = 1;
    p.sbtClosest = sbt;
    p.sbtClosest.raygenRecord = p.dRgClosest;
    p.sbtShadow = sbt;
    p.sbtShadow.raygenRecord = p.dRgShadow;

    ASTRORAY_OPTIX_TRAV_CUDA(cudaMalloc(reinterpret_cast<void**>(&p.dParams), sizeof(LaunchParams)));
}

// Traversable root published by optix_accel.cu.
unsigned long long g_root = 0;
int g_rootIsIas = 0;

void launch(const LaunchParams& lp, const OptixShaderBindingTable& sbt, int width) {
    Pipeline& p = P();
    // Legacy default stream: ordered with the wavefront <<<>>> launches around it.
    ASTRORAY_OPTIX_TRAV_CUDA(cudaMemcpyAsync(reinterpret_cast<void*>(p.dParams), &lp,
                                             sizeof(LaunchParams), cudaMemcpyHostToDevice, 0));
    ASTRORAY_OPTIX_TRAV_CHECK(optixLaunch(p.pipe, /*stream*/ 0, p.dParams, sizeof(LaunchParams),
                                          &sbt, static_cast<unsigned int>(width), 1, 1));
}

}  // namespace

OptixDeviceContext context() {
    return available() ? P().ctx : nullptr;
}

bool available() {
    Pipeline& p = P();
    std::lock_guard<std::mutex> lock(initMutex());
    if (!p.tried) {
        p.tried = true;
        try {
            initPipeline(p);
            p.ok = true;
        } catch (const std::exception& e) {
            // No retry per render: a device without RT cores or a broken
            // driver would pay the init cost on every call. Release what was
            // created; the process stays on the software BVH.
            destroyPipeline(p);
            p.ok = false;
            p.error = e.what();
            std::fprintf(stderr, "%s — GPU traversal stays on the software BVH\n", e.what());
            (void)cudaGetLastError();
        }
    }
    return p.ok;
}

std::string lastError() { return P().error; }

void setRoot(unsigned long long handle, int isIas) {
    g_root = handle;
    g_rootIsIas = isIas;
}

void traceClosest(const ClosestLaunch& c, int width) {
    if (width <= 0) return;
    LaunchParams lp{};
    lp.handle = g_root;
    lp.hasIas = g_rootIsIas;
    lp.closest = c;
    launch(lp, P().sbtClosest, width);
}

void traceShadow(const ShadowLaunch& s, int width) {
    if (width <= 0) return;
    LaunchParams lp{};
    lp.handle = g_root;
    lp.hasIas = g_rootIsIas;
    lp.shadow = s;
    launch(lp, P().sbtShadow, width);
}

}  // namespace optix_trav
}  // namespace astroray

#endif  // ASTRORAY_OPTIX_TRAVERSAL
