#!/usr/bin/env python3
"""pkg178 Stage 4 PR-1 — bake the thin-film CIE sensitivity LUT to Rec.709.

Mechanically ports Cycles' `ShaderManager::compute_thin_film_table`
(intern/cycles/scene/shader.cpp:932, Apache-2.0): load the precomputed,
frequency-resampled, Fourier-transformed CIE 1931 2deg XYZ CMFs
(`table_thin_film_cmf[512][6]`, intern/cycles/scene/shader.tables:1287,
Apache-2.0), multiply each entry by the working-space XYZ->RGB matrix (resampling
and FFT are linear, so this commutes), and normalize by the DC term (row 0) so
the CMF integrates to 1.

Astroray's working space is fixed linear Rec.709 (sRGB primaries, D65), so the
XYZ->RGB multiply is baked here at generation time — no runtime transform, unlike
Cycles which only knows the matrix at runtime.

Belcour & Barla 2017, ACM TOG 36(4):65, DOI 10.1145/3072959.3073620.

Usage:
    python doc/precompute/thin_film_table.py <path/to/cycles/shader.tables> \
        [--out include/astroray/thin_film_cie_table.h] [--check]

--check prints >=8 spot-check rows (raw XYZ -> baked RGB) for the evidence gate.
"""
import argparse
import re

# Linear-Rec.709 (sRGB primaries, D65) XYZ->RGB matrix. Rows = R,G,B.
# Bruce Lindbloom / IEC 61966-2-1; matches Blender's
# ColorSpaceManager::get_xyz_to_scene_linear_rgb() for the Rec.709 scene space.
XYZ_TO_REC709 = [
    [3.2404542, -1.5371385, -0.4985314],
    [-0.9692660, 1.8760108, 0.0415560],
    [0.0556434, -0.2040259, 1.0572252],
]

TABLE_SIZE = 512


def mat_vec(m, v):
    return [m[r][0] * v[0] + m[r][1] * v[1] + m[r][2] * v[2] for r in range(3)]


def parse_raw_table(path):
    """Parse `static const float table_thin_film_cmf[512][6] = { {..}, .. };`."""
    with open(path, "r", encoding="utf-8", errors="ignore") as fh:
        text = fh.read()
    m = re.search(r"table_thin_film_cmf\[512\]\[6\]\s*=\s*\{(.*?)\};", text, re.DOTALL)
    if not m:
        raise SystemExit("could not find table_thin_film_cmf[512][6] in " + path)
    body = m.group(1)
    rows = re.findall(r"\{([^{}]*)\}", body)
    if len(rows) != TABLE_SIZE:
        raise SystemExit(f"expected {TABLE_SIZE} rows, parsed {len(rows)}")
    out = []
    for row in rows:
        tokens = re.findall(r"[-+]?[0-9.]+(?:[eE][-+]?[0-9]+)?f?", row)
        vals = [float(x.rstrip("f")) for x in tokens]
        if len(vals) != 6:
            raise SystemExit(f"expected 6 values per row, got {len(vals)}: {row}")
        out.append(vals)
    return out


def bake(raw):
    """XYZ->RGB multiply + DC normalization. Returns [512][6] {reR,reG,reB,imR,imG,imB}."""
    baked = []
    norm = None
    for i, row in enumerate(raw):
        xyz_re = [row[0], row[1], row[2]]
        xyz_im = [row[3], row[4], row[5]]
        rgb_re = mat_vec(XYZ_TO_REC709, xyz_re)
        rgb_im = mat_vec(XYZ_TO_REC709, xyz_im)
        if i == 0:
            norm = [1.0 / rgb_re[c] for c in range(3)]
        baked.append([
            rgb_re[0] * norm[0], rgb_re[1] * norm[1], rgb_re[2] * norm[2],
            rgb_im[0] * norm[0], rgb_im[1] * norm[1], rgb_im[2] * norm[2],
        ])
    return baked


def write_header(baked, out_path):
    lines = []
    lines.append("#pragma once")
    lines.append("// ===========================================================================")
    lines.append("// pkg178 Stage 4 PR-1 — Rec.709-baked thin-film CIE sensitivity LUT.")
    lines.append("//")
    lines.append("// GENERATED by doc/precompute/thin_film_table.py — DO NOT EDIT BY HAND.")
    lines.append("//")
    lines.append("// Source: Cycles `table_thin_film_cmf[512][6]` (intern/cycles/scene/")
    lines.append("//   shader.tables:1287, Apache-2.0) — frequency-resampled + FFT'd CIE 1931")
    lines.append("//   2deg XYZ CMFs — with `ShaderManager::compute_thin_film_table`")
    lines.append("//   (intern/cycles/scene/shader.cpp:932, Apache-2.0) applied offline: the")
    lines.append("//   XYZ->linear-Rec.709 (sRGB primaries, D65) multiply + DC normalization.")
    lines.append("//   Belcour & Barla 2017, ACM TOG 36(4):65.")
    lines.append("//")
    lines.append("// Layout: [512][6] = {re_R, re_G, re_B, im_R, im_G, im_B}. Consumed by")
    lines.append("//   astroray::thinfilm::sensitivityRGB (thin_film_fresnel.h).")
    lines.append("// ===========================================================================")
    lines.append("")
    lines.append("namespace astroray {")
    lines.append("namespace thinfilm {")
    lines.append("")
    lines.append(f"inline constexpr float kThinFilmCieTable[{TABLE_SIZE}][6] = {{")
    for row in baked:
        cells = ", ".join(f"{v:+.8e}f" for v in row)
        lines.append(f"    {{{cells}}},")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace thinfilm")
    lines.append("}  // namespace astroray")
    lines.append("")
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))


def spot_check(raw, baked):
    idxs = [0, 1, 5, 17, 64, 128, 255, 383, 511]
    print("spot-check (idx : raw XYZ_re -> baked RGB_re | baked RGB_im):")
    for i in idxs:
        r = raw[i]
        b = baked[i]
        print(f"  [{i:3d}] xyz_re=({r[0]:+.4e},{r[1]:+.4e},{r[2]:+.4e}) "
              f"-> rgb_re=({b[0]:+.6f},{b[1]:+.6f},{b[2]:+.6f}) "
              f"rgb_im=({b[3]:+.6f},{b[4]:+.6f},{b[5]:+.6f})")
    # DC row must normalize to exactly 1 on the real channels, 0 on imaginary.
    b0 = baked[0]
    assert abs(b0[0] - 1.0) < 1e-6 and abs(b0[1] - 1.0) < 1e-6 and abs(b0[2] - 1.0) < 1e-6, b0
    assert abs(b0[3]) < 1e-9 and abs(b0[4]) < 1e-9 and abs(b0[5]) < 1e-9, b0
    print("  DC row (idx 0) real == 1, imag == 0 : PASS")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tables", help="path to Cycles shader.tables")
    ap.add_argument("--out", default="include/astroray/thin_film_cie_table.h")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    raw = parse_raw_table(args.tables)
    baked = bake(raw)
    if args.check:
        spot_check(raw, baked)
    write_header(baked, args.out)
    print(f"wrote {args.out} ({len(baked)} rows)")


if __name__ == "__main__":
    main()
