"""Offline generator for pkg10 spectral data files.

This is a build-time tool, not a runtime dependency. It regenerates the
checked-in data files under `data/spectra/` and the test oracle under
`tests/data/spectrum_reference.json`.

Run from the repo root:
    python scripts/generate_spectrum_data.py

Requirements:
    pip install "colour-science==0.4.7" numpy

Inputs:
    - CIE 1964 10 Degree Standard Observer x-bar, y-bar, z-bar
      (360-830 nm at 1 nm) from colour-science. The same table is
      published as a CSV at http://cvrl.ucl.ac.uk/ if a future refresh
      needs to bypass the Python dependency.
    - CIE Standard Illuminant D65 from colour-science
      (300-780 nm at 5 nm, linearly interpolated to 1 nm 360-830;
      values past 780 nm are extrapolated to 0).

Outputs:
    - data/spectra/cie_cmf.inc          (C++ constexpr CMF arrays)
    - data/spectra/illuminant_d65.inc   (C++ constexpr D65 SPD array)
    - tests/data/spectrum_reference.json (test oracle values)

The `rgb_to_spectrum_srgb.coeff` Jakob-Hanika LUT is vendored as-is
from https://github.com/geometrian/simple-spectral (MIT) and is NOT
regenerated by this script. See THIRD_PARTY.md for provenance.
"""

from __future__ import annotations

import json
import struct
from pathlib import Path

import numpy as np

try:
    import colour  # type: ignore
except ImportError as e:  # pragma: no cover
    raise SystemExit(
        "colour-science is required for this generator. "
        "Install with: pip install 'colour-science==0.4.7'"
    ) from e


REPO = Path(__file__).resolve().parents[1]
DATA_DIR = REPO / "data" / "spectra"
TEST_DATA_DIR = REPO / "tests" / "data"

LAMBDA_MIN = 360  # nm, inclusive
LAMBDA_MAX = 830  # nm, inclusive
LAMBDA_STEP = 1
LAMBDAS = np.arange(LAMBDA_MIN, LAMBDA_MAX + 1, LAMBDA_STEP, dtype=np.float64)


def load_cie_1964_10deg_cmf() -> np.ndarray:
    """Return (N,3) array of x-bar, y-bar, z-bar at LAMBDAS."""
    cmfs = colour.MSDS_CMFS["CIE 1964 10 Degree Standard Observer"]
    # colour-science already gives us 360-830 at 1 nm for this observer.
    values = np.asarray(cmfs.values, dtype=np.float64)
    domain = np.asarray(cmfs.wavelengths, dtype=np.float64)
    assert domain[0] == LAMBDA_MIN and domain[-1] == LAMBDA_MAX, (
        f"Unexpected CMF domain {domain[0]}..{domain[-1]}"
    )
    assert values.shape == (LAMBDAS.size, 3), f"Unexpected CMF shape {values.shape}"
    return values


def load_d65_spd() -> np.ndarray:
    """Return (N,) array of D65 relative SPD sampled at LAMBDAS.

    D65 is tabulated 300-780 nm at 5 nm. Values for 360-780 are
    linearly interpolated; 781-830 are zeros (eye is effectively blind
    there for a daylight-source check — this matches the treatment the
    Jakob-Hanika paper uses when computing sRGB tristimuli).
    """
    d65 = colour.SDS_ILLUMINANTS["D65"]
    src_lambdas = np.asarray(d65.wavelengths, dtype=np.float64)
    src_values = np.asarray(d65.values, dtype=np.float64)
    out = np.interp(LAMBDAS, src_lambdas, src_values, left=0.0, right=0.0)
    return out


def write_cmf_inc(cmf: np.ndarray, out_path: Path) -> None:
    """Emit include/astroray/data/spectra/cie_cmf.inc header."""
    n = cmf.shape[0]

    def fmt_row(arr: np.ndarray) -> str:
        pieces = []
        for i in range(0, arr.size, 8):
            chunk = arr[i : i + 8]
            line = "    " + ", ".join(f"{v:.8e}f" for v in chunk)
            if i + 8 < arr.size:
                line += ","
            pieces.append(line)
        return "\n".join(pieces)

    banner = (
        "// Auto-generated by scripts/generate_spectrum_data.py — do not edit by hand.\n"
        "// Source: CIE 1964 10 Degree Standard Observer CMF\n"
        "//         (public domain, http://cvrl.ucl.ac.uk/ — delivered here via\n"
        "//         colour-science 0.4.7 MSDS_CMFS table, cross-checked against cvrl).\n"
        f"// Range: {LAMBDA_MIN}-{LAMBDA_MAX} nm at {LAMBDA_STEP} nm ({n} samples).\n"
    )

    content = f"""{banner}
static constexpr int kCieCmfCount = {n};
static constexpr float kCieCmfLambdaMin = {float(LAMBDA_MIN)}f;
static constexpr float kCieCmfLambdaMax = {float(LAMBDA_MAX)}f;
static constexpr float kCieCmfLambdaStep = {float(LAMBDA_STEP)}f;

static constexpr float kCieCmfX[{n}] = {{
{fmt_row(cmf[:, 0])}
}};

static constexpr float kCieCmfY[{n}] = {{
{fmt_row(cmf[:, 1])}
}};

static constexpr float kCieCmfZ[{n}] = {{
{fmt_row(cmf[:, 2])}
}};
"""
    out_path.write_text(content, encoding="utf-8")


def write_d65_inc(d65: np.ndarray, out_path: Path) -> None:
    """Emit data/spectra/illuminant_d65.inc header."""
    n = d65.size

    def fmt_row(arr: np.ndarray) -> str:
        pieces = []
        for i in range(0, arr.size, 8):
            chunk = arr[i : i + 8]
            line = "    " + ", ".join(f"{v:.6e}f" for v in chunk)
            if i + 8 < arr.size:
                line += ","
            pieces.append(line)
        return "\n".join(pieces)

    banner = (
        "// Auto-generated by scripts/generate_spectrum_data.py — do not edit by hand.\n"
        "// Source: CIE Standard Illuminant D65 (public domain).\n"
        "//         300-780 nm @ 5 nm (colour-science 0.4.7), linearly\n"
        "//         interpolated to 1 nm over 360-830 nm. 781-830 nm = 0\n"
        "//         (well below the eye's response).\n"
        f"// Range: {LAMBDA_MIN}-{LAMBDA_MAX} nm at {LAMBDA_STEP} nm ({n} samples).\n"
    )

    content = f"""{banner}
static constexpr int kD65Count = {n};
static constexpr float kD65LambdaMin = {float(LAMBDA_MIN)}f;
static constexpr float kD65LambdaMax = {float(LAMBDA_MAX)}f;
static constexpr float kD65LambdaStep = {float(LAMBDA_STEP)}f;

static constexpr float kD65Spd[{n}] = {{
{fmt_row(d65)}
}};
"""
    out_path.write_text(content, encoding="utf-8")


def parse_jakob_hanika_coeff(path: Path):
    """Return (res, scale, coeffs) from the Jakob-Hanika rgb2spec file.

    Format (little-endian):
        char magic[4];            // 'SPEC'
        uint32_t res;
        float scale[res];
        float coeffs[3][res][res][res][3];
    """
    data = path.read_bytes()
    assert data[:4] == b"SPEC", f"bad magic: {data[:4]!r}"
    (res,) = struct.unpack_from("<I", data, 4)
    off = 8
    scale = np.frombuffer(data, dtype="<f4", count=res, offset=off)
    off += res * 4
    n_coeffs = 3 * res * res * res * 3
    coeffs = np.frombuffer(data, dtype="<f4", count=n_coeffs, offset=off)
    coeffs = coeffs.reshape(3, res, res, res, 3).astype(np.float64)
    return res, scale.astype(np.float64), coeffs


def fma_sigmoid(c0: float, c1: float, c2: float, lam: float) -> float:
    """Evaluate Jakob-Hanika sigmoid: s( c0*lam^2 + c1*lam + c2 )."""
    x = (c0 * lam + c1) * lam + c2
    if np.isinf(x):
        return 1.0 if x > 0 else 0.0
    return 0.5 + x / (2.0 * np.sqrt(1.0 + x * x))


def eval_rgb_to_spectrum(rgb: np.ndarray, res: int, scale: np.ndarray,
                         coeffs: np.ndarray, lambdas: np.ndarray) -> np.ndarray:
    """Replicate the Jakob-Hanika LUT lookup for sRGB albedo.

    This is what the C++ runtime does; we reproduce it here so the test
    oracle is internally consistent with the LUT we ship.
    """
    rgb = np.clip(rgb, 0.0, 1.0)
    # Pick the largest channel (i)
    i = int(np.argmax(rgb))
    # Map to LUT coords
    others = [(i + 1) % 3, (i + 2) % 3]
    v_max = rgb[i]
    if v_max <= 1e-8:
        # Black: return near-zero spectrum (coeffs yield ~0)
        return np.zeros_like(lambdas)
    x = rgb[others[0]] / v_max
    y = rgb[others[1]] / v_max
    # Find z-slice via `scale` (non-uniform Y axis)
    # scale is monotonic increasing in [0,1]; invert via searchsorted.
    # (simple-spectral applies this to v_max directly)
    z = v_max
    # bilinear-ish trilinear lookup
    xi = x * (res - 1)
    yi = y * (res - 1)
    # z uses the scale table
    # find k such that scale[k] <= z <= scale[k+1]
    k = int(np.clip(np.searchsorted(scale, z) - 1, 0, res - 2))
    t_z = (z - scale[k]) / max(scale[k + 1] - scale[k], 1e-20)
    x0, y0 = int(np.clip(xi, 0, res - 2)), int(np.clip(yi, 0, res - 2))
    t_x, t_y = xi - x0, yi - y0

    def lerp3(a, b, c, d, tx, ty):
        return (a * (1 - tx) + b * tx) * (1 - ty) + (c * (1 - tx) + d * tx) * ty

    # Gather 8 corners of the trilinear box: coeffs[i, z, y, x, coeff]
    c000 = coeffs[i, k,     y0,     x0    ]
    c100 = coeffs[i, k,     y0,     x0 + 1]
    c010 = coeffs[i, k,     y0 + 1, x0    ]
    c110 = coeffs[i, k,     y0 + 1, x0 + 1]
    c001 = coeffs[i, k + 1, y0,     x0    ]
    c101 = coeffs[i, k + 1, y0,     x0 + 1]
    c011 = coeffs[i, k + 1, y0 + 1, x0    ]
    c111 = coeffs[i, k + 1, y0 + 1, x0 + 1]

    c_low = lerp3(c000, c100, c010, c110, t_x, t_y)
    c_high = lerp3(c001, c101, c011, c111, t_x, t_y)
    c = c_low * (1 - t_z) + c_high * t_z  # (3,) sigmoid coefficients

    # The LUT's lambda mapping: coefficients are optimized over 360..830
    # with "normalized lambda" in [0, 1] — but simple-spectral and the
    # paper use a direct (λ - 360)/(830-360) remap baked into the
    # coefficient fit. The sigmoid is evaluated at actual nm.
    # Per the paper: S(λ) = sigmoid(c0*λ^2 + c1*λ + c2), λ in nm.
    result = np.empty_like(lambdas)
    for j, lam in enumerate(lambdas):
        result[j] = fma_sigmoid(c[0], c[1], c[2], lam)
    return result


def compute_d65_xyz(d65: np.ndarray, cmf: np.ndarray, lambdas: np.ndarray) -> tuple[float, float, float]:
    """Numerically integrate D65 * CMF using the trapezoid rule."""
    d_lam = lambdas[1:] - lambdas[:-1]
    # trapezoid midpoint weight
    x_int = np.sum(0.5 * d_lam * (d65[:-1] * cmf[:-1, 0] + d65[1:] * cmf[1:, 0]))
    y_int = np.sum(0.5 * d_lam * (d65[:-1] * cmf[:-1, 1] + d65[1:] * cmf[1:, 1]))
    z_int = np.sum(0.5 * d_lam * (d65[:-1] * cmf[:-1, 2] + d65[1:] * cmf[1:, 2]))
    # Normalize to Y=1.0 (relative colorimetry for a perfect white)
    k = 1.0 / y_int
    return (x_int * k, y_int * k, z_int * k)


def main() -> int:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    TEST_DATA_DIR.mkdir(parents=True, exist_ok=True)

    cmf = load_cie_1964_10deg_cmf()
    d65 = load_d65_spd()

    write_cmf_inc(cmf, DATA_DIR / "cie_cmf.inc")
    write_d65_inc(d65, DATA_DIR / "illuminant_d65.inc")
    print(f"wrote {DATA_DIR / 'cie_cmf.inc'} ({cmf.shape[0]} CMF samples)")
    print(f"wrote {DATA_DIR / 'illuminant_d65.inc'} ({d65.size} D65 samples)")

    # D65 whitepoint reference
    xyz_d65 = compute_d65_xyz(d65, cmf, LAMBDAS)
    print(f"D65 XYZ (from shipped data): {xyz_d65}")

    # Jakob-Hanika LUT oracle: sanity-check the .coeff by evaluating a
    # handful of sRGB primaries and saving the expected spectrum samples.
    coeff_path = DATA_DIR / "rgb_to_spectrum_srgb.coeff"
    if not coeff_path.exists():
        raise SystemExit(f"expected LUT file at {coeff_path}; see THIRD_PARTY.md")
    res, scale, coeffs = parse_jakob_hanika_coeff(coeff_path)
    print(f"parsed Jakob-Hanika LUT: res={res}, scale[0]={scale[0]:.4f}, scale[-1]={scale[-1]:.4f}")

    test_lambdas = np.array([450.0, 550.0, 620.0, 720.0], dtype=np.float64)
    primaries = {
        "black":   (0.0, 0.0, 0.0),
        "white":   (1.0, 1.0, 1.0),
        "mid_grey": (0.5, 0.5, 0.5),
        "red":     (1.0, 0.0, 0.0),
        "green":   (0.0, 1.0, 0.0),
        "blue":    (0.0, 0.0, 1.0),
    }
    rgb_samples = {}
    for name, rgb in primaries.items():
        spectrum = eval_rgb_to_spectrum(np.array(rgb), res, scale, coeffs, test_lambdas)
        rgb_samples[name] = {
            "rgb": list(rgb),
            "wavelengths_nm": test_lambdas.tolist(),
            "expected_spectrum": spectrum.tolist(),
        }
        print(f"  {name:9s} {rgb} -> spectrum {spectrum.round(5).tolist()}")

    reference = {
        "generator": "scripts/generate_spectrum_data.py",
        "source": "colour-science 0.4.7 + Jakob-Hanika 2019 LUT (simple-spectral)",
        "wavelength_range_nm": [LAMBDA_MIN, LAMBDA_MAX],
        "wavelength_step_nm": LAMBDA_STEP,
        "d65_xyz_whitepoint": {
            "X": xyz_d65[0], "Y": xyz_d65[1], "Z": xyz_d65[2],
            "cie_nominal": {"X": 0.95047, "Y": 1.0, "Z": 1.08883},
        },
        "jakob_hanika_samples": rgb_samples,
        "cmf_first_row": cmf[0].tolist(),   # sanity check in C++ tests
        "cmf_last_row": cmf[-1].tolist(),
        "d65_sample_at_555nm": float(d65[LAMBDAS.tolist().index(555.0)]),
    }
    out = TEST_DATA_DIR / "spectrum_reference.json"
    out.write_text(json.dumps(reference, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
