# EmbedBinary.cmake — write a binary file as a C++ byte array (pkg299).
#
# cmake -DIN=<file> -DOUT=<file.cpp> -DSYM=<symbol> -P EmbedBinary.cmake
#
# Emits:
#   extern "C" const unsigned char <SYM>[];
#   extern "C" const unsigned long long <SYM>_size;
# Used to embed the OptiX-IR module (src/gpu/optix/optix_trace_programs.cu) in
# the engine so the .pyd carries its own OptiX programs.

file(READ "${IN}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _size "${_hexlen} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
# Break the initializer into lines of 32 bytes (160 chars) for the compiler.
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" _bytes "${_bytes}")
file(WRITE "${OUT}"
"// Generated by cmake/EmbedBinary.cmake from ${IN}. Do not edit.\n"
"extern \"C\" const unsigned char ${SYM}[] = {\n${_bytes}\n};\n"
"extern \"C\" const unsigned long long ${SYM}_size = ${_size}ull;\n")
